# Generated by Django 5.0.6 on 2024-05-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('d_o_b', models.DateField()),
                ('id_number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
